# alert -> drop pour categories haute confiance
re:"ET DROP" "alert" "drop"
re:"ET CINS" "alert" "drop"
re:"ET WEB_SERVER.*/bin/sh" "alert" "drop"
re:"ET WEB_SERVER.*PHP" "alert" "drop"
re:"ET WEB_SERVER.*ThinkPHP" "alert" "drop"
re:"ET WEB_SERVER.*WebShell" "alert" "drop"
re:"ET WEB_SERVER.*SQL Injection" "alert" "drop"
re:"ET WEB_SPECIFIC_APPS.*Command Injection" "alert" "drop"
re:"ET SCAN Zmap" "alert" "drop"
re:"ET MALWARE" "alert" "drop"
re:"ET CNC" "alert" "drop"
re:"ET TROJAN" "alert" "drop"
re:"ET EXPLOIT" "alert" "drop"
re:"GPL DNS named version attempt" "alert" "drop"
